name: Auto merge
on:
  pull_request:
    branches:
      - main
jobs:
  auto-merge:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
    # if: ${{ github.event.pull_request.user.login == 'git-form' }}
    steps:
      - run: |
          echo "${{ github.event.pull_request.user.login }}"
          # gh pr merge ${{ github.event.pull_request.number }} --auto
