name: Auto merge
on:
  pull_request:
    branches:
      - main
jobs:
  auto-merge:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
    if: ${{ github.event.pull_request.user.login == 'git-form[bot]' }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          gh pr merge ${{ github.event.pull_request.number }} --auto --squash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
